cfg = {
    'data_root': '/data1/nuscenes',
    'version': 'v1.0-trainval',
    'nusc_val_fpath': 'tools/gen_occ_nus/nuscenes_val_list.txt',
    'split': 'train',
    'save_dir': './__occ/dense_occ_debug_all',
    'log_level': 'DEBUG',
    'scene_range': [0, 850],

    # Surround Setting
    'voxel_size': [0.5, 0.5, 0.5],
    'pc_range': [-50, -50, -5, 50, 50, 3],
    'occ_size': [200, 200, 16],

    # Custom Setting
    # 'voxel_size': [0.15, 0.15, 1],
    # 'pc_range': [-15, -30, -10, 15, 30, 10],
    # 'occ_size': [200, 400, 20],

    'self_range': [3.0, 3.0, 3.0],
    'mesh': {
        'depth': 10,
        'min_density': 0.1,
        # Notice: poisson reconstruction threads, -1 is a disaster
        'n_threads': 8,
        'downsample': False,
        'max_nn': 20,
    },

    # where to load seg label, 'lidar_seg' or 'image_seg', if 'image_seg'
    # means use semantic segmentation to get seg mask, then project lidar
    # point cloud to image to get label of each point cloud; Same to lidar
    # seg label, image seg label only loaded on key frame
    'seg_label': 'image_seg',

    # >>> setting for 'image_seg'
    # dir to save seg mask, e.g. seg_root/image_name.png
    'seg_root': './data/nusc_seg/panoptic_seg_merge',
    'seg_vis_root': './data/nusc_seg/panoptic_seg_merge_vis',
    'cam_name_dic': dict(CAM_FRONT_LEFT=0, CAM_FRONT=1, CAM_FRONT_RIGHT=2,
                         CAM_BACK_LEFT=3, CAM_BACK=4, CAM_BACK_RIGHT=5),
    'ori_img_h': 900,
    'ori_img_w': 1600,
    # Only load key frame seg label
    'is_only_key_frame': True,
    'seg_default_cls': -1,
    'is_assign_empty': True,
    'is_save_vis_fig': False,
    'vis_fig_size': (28, 11),
    'is_voxel_MA': True,
    # <<< setting for 'image_seg'
}

labels = dict(
    nusc_id2name={
        0: 'noise',
        1: 'animal',
        2: 'human.pedestrian.adult',
        3: 'human.pedestrian.child',
        4: 'human.pedestrian.construction_worker',
        5: 'human.pedestrian.personal_mobility',
        6: 'human.pedestrian.police_officer',
        7: 'human.pedestrian.stroller',
        8: 'human.pedestrian.wheelchair',
        9: 'movable_object.barrier',
        10: 'movable_object.debris',
        11: 'movable_object.pushable_pullable',
        12: 'movable_object.trafficcone',
        13: 'static_object.bicycle_rack',
        14: 'vehicle.bicycle',
        15: 'vehicle.bus.bendy',
        16: 'vehicle.bus.rigid',
        17: 'vehicle.car',
        18: 'vehicle.construction',
        19: 'vehicle.emergency.ambulance',
        20: 'vehicle.emergency.police',
        21: 'vehicle.motorcycle',
        22: 'vehicle.trailer',
        23: 'vehicle.truck',
        24: 'flat.driveable_surface',
        25: 'flat.other',
        26: 'flat.sidewalk',
        27: 'flat.terrain',
        28: 'static.manmade',
        29: 'static.other',
        30: 'static.vegetation',
        31: 'vehicle.ego',
    },
    occ_id2name={
        0: 'noise',
        1: 'barrier',
        2: 'bicycle',
        3: 'bus',
        4: 'car',
        5: 'construction_vehicle',
        6: 'motorcycle',
        7: 'pedestrian',
        8: 'traffic_cone',
        9: 'trailer',
        10: 'truck',
        11: 'driveable_surface',
        12: 'other_flat',
        13: 'sidewalk',
        14: 'terrain',
        15: 'manmade',
        16: 'vegetation',
        17: 'sky'
    },
    nusc_id2occ_id={
        1: 0,
        5: 0,
        7: 0,
        8: 0,
        10: 0,
        11: 0,
        13: 0,
        19: 0,
        20: 0,
        0: 0,
        29: 0,
        31: 0,
        9: 1,
        14: 2,
        15: 3,
        16: 3,
        17: 4,
        18: 5,
        21: 6,
        2: 7,
        3: 7,
        4: 7,
        6: 7,
        12: 8,
        22: 9,
        23: 10,
        24: 11,
        25: 12,
        26: 13,
        27: 14,
        28: 15,
        30: 16,
    },
    seg_id2name={
        0: 'background',
        1: 'road',
        2: 'tree',
        3: 'sky',
        4: 'person',
        5: 'car',
        6: 'truck',
        7: 'bus',
        8: 'tricycle_and_trailer',
        9: 'motorcycle',
        10: 'bicycle',
        11: 'fence',
        12: 'cone',
        13: 'pole',
        14: 'static',
        15: 'animal',
        16: 'baby-chair'
    },
    seg_id2occ_id={
        0: 12,
        1: 11,
        2: 16,
        3: -1,      # 天空, 没有意义
        4: 7,
        5: 4,
        6: 10,
        7: 3,
        8: 9,
        9: 6,
        10: 2,
        11: 1,
        12: 8,
        13: 8,
        14: 15,
        15: 5,      # for display
        16: 2,
        -1: -1,     # default cls
    }
)
