
cfg = {
    'data_root': '/data1/nuscenes',
    'version': 'v1.0-mini',
    'nusc_val_fpath': 'tools/gen_occ_nus/nuscenes_val_list.txt',
    'split': 'train',
    'save_dir': './dense_occ',
    'log_path': './dense_occ.log',
    'scene_range': [0, 850],
    'voxel_size': [0.5, 0.5, 0.5],
    'pc_range': [-50, -50, -5, 50, 50, 3],
    'occ_size': [200, 200, 16],
    'self_range': [3.0, 3.0, 3.0],
    'mesh': {
        'depth': 10,
        'min_density': 0.1,
        'n_threads': -1,
        'downsample': False,
        'max_nn': 20,
    },
}


labels = dict(
    nusc_id2name={
        0: 'noise',
        1: 'animal',
        2: 'human.pedestrian.adult',
        3: 'human.pedestrian.child',
        4: 'human.pedestrian.construction_worker',
        5: 'human.pedestrian.personal_mobility',
        6: 'human.pedestrian.police_officer',
        7: 'human.pedestrian.stroller',
        8: 'human.pedestrian.wheelchair',
        9: 'movable_object.barrier',
        10: 'movable_object.debris',
        11: 'movable_object.pushable_pullable',
        12: 'movable_object.trafficcone',
        13: 'static_object.bicycle_rack',
        14: 'vehicle.bicycle',
        15: 'vehicle.bus.bendy',
        16: 'vehicle.bus.rigid',
        17: 'vehicle.car',
        18: 'vehicle.construction',
        19: 'vehicle.emergency.ambulance',
        20: 'vehicle.emergency.police',
        21: 'vehicle.motorcycle',
        22: 'vehicle.trailer',
        23: 'vehicle.truck',
        24: 'flat.driveable_surface',
        25: 'flat.other',
        26: 'flat.sidewalk',
        27: 'flat.terrain',
        28: 'static.manmade',
        29: 'static.other',
        30: 'static.vegetation',
        31: 'vehicle.ego',
    },
    occ_id2name={
        0: 'noise',
        1: 'barrier',
        2: 'bicycle',
        3: 'bus',
        4: 'car',
        5: 'construction_vehicle',
        6: 'motorcycle',
        7: 'pedestrian',
        8: 'traffic_cone',
        9: 'trailer',
        10: 'truck',
        11: 'driveable_surface',
        12: 'other_flat',
        13: 'sidewalk',
        14: 'terrain',
        15: 'manmade',
        16: 'vegetation',
    },
    nusc_id2occ_id={
        1: 0,
        5: 0,
        7: 0,
        8: 0,
        10: 0,
        11: 0,
        13: 0,
        19: 0,
        20: 0,
        0: 0,
        29: 0,
        31: 0,
        9: 1,
        14: 2,
        15: 3,
        16: 3,
        17: 4,
        18: 5,
        21: 6,
        2: 7,
        3: 7,
        4: 7,
        6: 7,
        12: 8,
        22: 9,
        23: 10,
        24: 11,
        25: 12,
        26: 13,
        27: 14,
        28: 15,
        30: 16,
    }
)
